#version: "3"

services:
  #### Base trick runtimes

  trick-test:
    image: nasatrick/trick-test-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: trick-test
    volumes:
      - ./test_reports:/opt/trick/trick_test
#    command:
#      - /bin/bash

  trick-test-with-koviz:
    image: nasatrick/trick-test-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: trick-test-with-koviz
    volumes:
      - ./test_reports:/opt/trick/trick_test
#    command:
#      - /bin/bash

  cli-runtime:
    image: nasatrick/cli-runtime-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: cli-runtime
    ports:
      - "9001:9001" # default port of trick variable server
    volumes:
      - ../trick_sims:/opt/trick_sims

  gui-runtime:
    image: nasatrick/gui-runtime-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: gui-runtime
    volumes:
      - /dev/shm:/dev/shm # not necessary, but used by vnc if provided
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC

  koviz-gui-runtime:
    extends:
      service: gui-runtime
    image: nasatrick/gui-koviz-runtime-${OS_ID}
    build:
      target: koviz-gui-runtime

  ####  GL accelerated runtimes
  mesa-gl-default-docker:
    image: nasatrick/mesa-gl-docker-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: gl-runtime
    volumes:
      - /dev/shm:/dev/shm # not necessary, but used by vnc if provided
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      DEBUG: "true"
      DISPLAY: ":1"
      VGL_DISPLAY: "${CARD_NUMBER:-/dev/dri/card1}"
      TIGER_VNC_VIRTUALGL: "true"
      # VNC_RESOLUTION: "3840x2160"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
      - "${CARD_NUMBER:-card1}:${CARD_NUMBER:-card1}:rwm"
    tty: true
    command:
      - /bin/bash
    user: "1000:1000"
    group_add:
      - video
      - render
      - ${VIDEO_GROUP_NUMBER:-1}
      - ${RENDER_GROUP_NUMBER:-2}

  # note: this is intended to only be used when in the docker "rootless" context
  # not the "default" context, which is root-full
  mesa-gl-rootless-docker:
    image: nasatrick/mesa-gl-docker-${OS_ID}
    profiles:
      - single-image
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      target: gl-runtime
    volumes:
      - /dev/shm:/dev/shm # not necessary, but used by vnc if provided
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      DEBUG: "true"
      DISPLAY: ":1"
      VGL_DISPLAY: "${CARD_NUMBER:-/dev/dri/card1}"
      TIGER_VNC_VIRTUALGL: "true"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
      - "${CARD_NUMBER:-card1}:${CARD_NUMBER:-card1}:rwm"
    tty: true
    command:
      - /bin/bash
    user: "root"
    group_add:
      - video
      - render
      - ${VIDEO_GROUP_NUMBER:-1}
      - ${RENDER_GROUP_NUMBER:-2}

  #### Example minimal distributable runtimes for Trick Billiards sim
  mesa-gl-billiards-sim-default-docker:
    extends:
      service: mesa-gl-default-docker
    image: nasatrick/mesa-gl-billiards-sim-${OS_ID}
    build:
      target: billiards-gl-runtime

  mesa-gl-billiards-sim-rootless-docker:
    extends:
      service: mesa-gl-rootless-docker
    image: nasatrick/mesa-gl-billiards-sim-${OS_ID}
    build:
      target: billiards-gl-runtime

  #### Example minimal distributable runtime for Trick Sun sim
  sun-sim-cli-runtime:
    image: nasatrick/sun-sim-cli-runtime-${OS_ID}
    extends:
      service: cli-runtime
    build:
      target: sun-sim-cli-runtime

  sun-sim-gui-runtime:
    image: nasatrick/sun-sim-gui-runtime-${OS_ID}
    extends:
      service: gui-runtime
    build:
      target: sun-sim-gui-runtime

  #### Example minimal distributable runtimes for Trick Koviz spring sim visualization examples
  spring-sim-gui-runtime:
    image: nasatrick/spring-sim-gui-runtime-${OS_ID}
    extends:
      service: gui-runtime
    build:
      target: spring-sim-gui-runtime

  mesa-gl-spring-sim-default-docker:
    extends:
      service: mesa-gl-default-docker
    image: nasatrick/mesa-gl-spring-sim-${OS_ID}
    build:
      target: spring-sim-gl-runtime

  mesa-gl-spring-sim-rootless-docker:
    extends:
      service: mesa-gl-rootless-docker
    image: nasatrick/mesa-gl-spring-sim-${OS_ID}
    build:
      target: spring-sim-gl-runtime

  #### Example distributed runtime for Trick Cannon web-sim
  cannon-sim-server-runtime:
    scale: 1
    profiles:
      - distributed-cannon-sim
    image: nasatrick/cannon-sim-cli-runtime-${OS_ID}
    extends:
      service: cli-runtime
    build:
      target: cannon-sim-cli-runtime
    networks:
      sim:
    ports:
      - "9001:9001" # Trick variable server
      - "8888:8888" # civetweb REST API + websocket server

  cannon-sim-gui-runtime:
    scale: 1
    profiles:
      - distributed-cannon-sim
    image: nasatrick/cannon-sim-gui-runtime-${OS_ID}
    extends:
      service: gui-runtime
    build:
      target: cannon-sim-gui-runtime
    networks:
      sim:

networks:
  sim: